/*
 */
package com.iad.gui;

import com.iad.statepattern01.CaffeEvent;
import com.iad.statepattern01.CaffeProntoEvent;
import com.iad.statepattern01.RestoEvent;
import com.iad.statepattern01.RitiratoEvent;
import com.iad.statepattern01.SoldiEvent;
import com.iad.statepattern01.State;

/**
 *
 * @author use
 */
public class DistributoreAutomaticoGrafico extends javax.swing.JFrame implements CompagnoDellAutoma {

    private State automa = new AutomatonGui(this);

    /**
     * Creates new form DistributoreAutomaticoGrafico
     */
    public DistributoreAutomaticoGrafico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton10cent = new javax.swing.JButton();
        jButton20cent = new javax.swing.JButton();
        jButton50cent = new javax.swing.JButton();
        jButton1euro = new javax.swing.JButton();
        jButton2euro = new javax.swing.JButton();
        jLabelMessaggio = new javax.swing.JLabel();
        jButtonCaffe = new javax.swing.JButton();
        jButtonResto = new javax.swing.JButton();
        jButtonCoffeeReady = new javax.swing.JButton();
        jButtonRitirato = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton10cent.setText("0.10€");
        jButton10cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10centActionPerformed(evt);
            }
        });

        jButton20cent.setText("0.20€");
        jButton20cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20centActionPerformed(evt);
            }
        });

        jButton50cent.setText("0.50€");
        jButton50cent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton50centActionPerformed(evt);
            }
        });

        jButton1euro.setText("1.00€");
        jButton1euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1euroActionPerformed(evt);
            }
        });

        jButton2euro.setText("2.00€");
        jButton2euro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2euroActionPerformed(evt);
            }
        });

        jLabelMessaggio.setText("Questo è un testo");

        jButtonCaffe.setText("Caffè");
        jButtonCaffe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaffeActionPerformed(evt);
            }
        });

        jButtonResto.setText("Resto");
        jButtonResto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRestoActionPerformed(evt);
            }
        });

        jButtonCoffeeReady.setText("Caffè Pronto");
        jButtonCoffeeReady.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCoffeeReadyActionPerformed(evt);
            }
        });

        jButtonRitirato.setText("Caffè Ritirato");
        jButtonRitirato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRitiratoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMessaggio, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton10cent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton20cent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton50cent)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1euro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2euro)))
                        .addContainerGap(150, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonCaffe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonResto)
                        .addGap(62, 62, 62))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonCoffeeReady)
                            .addComponent(jButtonRitirato))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton10cent)
                    .addComponent(jButton20cent)
                    .addComponent(jButton50cent)
                    .addComponent(jButton1euro)
                    .addComponent(jButton2euro))
                .addGap(18, 18, 18)
                .addComponent(jLabelMessaggio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCaffe)
                    .addComponent(jButtonResto))
                .addGap(35, 35, 35)
                .addComponent(jButtonCoffeeReady)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonRitirato)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton10centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10centActionPerformed
        automa.next(new SoldiEvent(0.10));
    }//GEN-LAST:event_jButton10centActionPerformed

    private void jButton20centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20centActionPerformed
        automa.next(new SoldiEvent(0.20));
    }//GEN-LAST:event_jButton20centActionPerformed

    private void jButton50centActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton50centActionPerformed
        automa.next(new SoldiEvent(0.50));
    }//GEN-LAST:event_jButton50centActionPerformed

    private void jButton1euroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1euroActionPerformed
        automa.next(new SoldiEvent(1.00));
    }//GEN-LAST:event_jButton1euroActionPerformed

    private void jButton2euroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2euroActionPerformed
        automa.next(new SoldiEvent(2.00));
    }//GEN-LAST:event_jButton2euroActionPerformed

    private void jButtonCaffeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaffeActionPerformed
        automa.next(new CaffeEvent());
    }//GEN-LAST:event_jButtonCaffeActionPerformed

    private void jButtonRestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRestoActionPerformed
        automa.next(new RestoEvent());
    }//GEN-LAST:event_jButtonRestoActionPerformed

    private void jButtonCoffeeReadyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCoffeeReadyActionPerformed
        automa.next(new CaffeProntoEvent());
    }//GEN-LAST:event_jButtonCoffeeReadyActionPerformed

    private void jButtonRitiratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRitiratoActionPerformed
        automa.next(new RitiratoEvent());
    }//GEN-LAST:event_jButtonRitiratoActionPerformed

    @Override
    public void mostraMessaggio(String msg) {
        jLabelMessaggio.setText(msg);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistributoreAutomaticoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistributoreAutomaticoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistributoreAutomaticoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistributoreAutomaticoGrafico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistributoreAutomaticoGrafico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10cent;
    private javax.swing.JButton jButton1euro;
    private javax.swing.JButton jButton20cent;
    private javax.swing.JButton jButton2euro;
    private javax.swing.JButton jButton50cent;
    private javax.swing.JButton jButtonCaffe;
    private javax.swing.JButton jButtonCoffeeReady;
    private javax.swing.JButton jButtonResto;
    private javax.swing.JButton jButtonRitirato;
    private javax.swing.JLabel jLabelMessaggio;
    // End of variables declaration//GEN-END:variables
}
